# This code will build the Java project with Maven 

name: Build with Maven
on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, review_requested]
jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Project
        run: mvn -B verify 